urls.py
# ##############################################################################
#
#    OSIS stands for Open Student Information System. It's an application
#    designed to manage the core business of higher education institutions,
#    such as universities, faculties, institutes and professional schools.
#    The core business involves the administration of students, teachers,
#    courses, programs and so on.
#
#    Copyright (C) 2015-2023 Université catholique de Louvain (http://www.uclouvain.be)
#
#    This program is free software: you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation, either version 3 of the License, or
#    (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    A copy of this license - GNU General Public License - is available
#    at the root of the source code of this program.  If not,
#    see http://www.gnu.org/licenses/.
#
# ##############################################################################

from django.conf import settings

from osis_common.utils.file_router import FileRouter

app_name = 'parcours_doctoral'

file_router = FileRouter()
urlpatterns = file_router('parcours_doctoral/contrib/views')

if settings.DEBUG:
    import logging

    logger = logging.getLogger(__name__)
    logger.debug("\n" + file_router.debug(urlpatterns))

contrib/forms/admissibility.py
# ##############################################################################
#
#  OSIS stands for Open Student Information System. It's an application
#  designed to manage the core business of higher education institutions,
#  such as universities, faculties, institutes and professional schools.
#  The core business involves the administration of students, teachers,
#  courses, programs and so on.
#
#  Copyright (C) 2015-2025 Université catholique de Louvain (http://www.uclouvain.be)
#
#  This program is free software: you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation, either version 3 of the License, or
#  (at your option) any later version.
#
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.
#
#  A copy of this license - GNU General Public License - is available
#  at the root of the source code of this program.  If not,
#  see http://www.gnu.org/licenses/.
#
# ##############################################################################
from django import forms
from django.utils.translation import gettext_lazy as _

from parcours_doctoral.contrib.forms import CustomDateInput, DoctorateFileUploadField


class AdmissibilityForm(forms.Form):
    titre_these = forms.CharField(
        label=_('Thesis title'),
        max_length=255,
    )

    date_envoi_manuscrit = forms.DateField(
        label=_('Date of manuscript submission to the thesis exam board'),
        required=False,
        widget=CustomDateInput,
    )

    date_decision = forms.DateField(
        label=_('Date of admissibility decision'),
        help_text=_(
            'The admissibility decision date is chosen collectively by the board and in agreement with the PhD student.'
        ),
        required=False,
        widget=CustomDateInput,
    )


class JuryMemberAdmissibilityForm(forms.Form):
    proces_verbal = DoctorateFileUploadField(
        label=_('Admissibility minutes'),
        required=False,
    )
    avis_jury = DoctorateFileUploadField(
        label=_('Thesis exam board opinion'),
        required=False,
    )

contrib/forms/authorization_distribution.py
# ##############################################################################
#
#  OSIS stands for Open Student Information System. It's an application
#  designed to manage the core business of higher education institutions,
#  such as universities, faculties, institutes and professional schools.
#  The core business involves the administration of students, teachers,
#  courses, programs and so on.
#
#  Copyright (C) 2015-2025 Université catholique de Louvain (http://www.uclouvain.be)
#
#  This program is free software: you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation, either version 3 of the License, or
#  (at your option) any later version.
#
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.
#
#  A copy of this license - GNU General Public License - is available
#  at the root of the source code of this program.  If not,
#  see http://www.gnu.org/licenses/.
#
# ##############################################################################
from dal import forward
from django import forms
from django.contrib.postgres.forms import SimpleArrayField
from django.utils.translation import gettext_lazy as _

from parcours_doctoral.contrib.enums.authorization_distribution import (
    TypeModalitesDiffusionThese,
)
from parcours_doctoral.contrib.forms import (
    EMPTY_CHOICE,
    CustomDateInput,
    get_language_initial_choices,
)
from parcours_doctoral.contrib.forms.autocomplete import ListSelect2, TagSelect2
from parcours_doctoral.contrib.views.autocomplete import LANGUAGE_UNDECIDED


class AuthorizationDistributionForm(forms.Form):
    sources_financement = forms.CharField(
        label=_('Sources of funding throughout PhD'),
        required=False,
        max_length=100,
    )

    resume_anglais = forms.CharField(
        label=_('Summary in English'),
        required=False,
        max_length=100,
    )

    resume_autre_langue = forms.CharField(
        label=_('Summary in other language'),
        required=False,
        max_length=100,
    )

    langue_redaction_these = forms.ChoiceField(
        label=_('Thesis language'),
        widget=ListSelect2(
            url='parcours_doctoral:autocomplete:language',
            attrs={
                'data-html': True,
            },
            forward=(forward.Const(True, 'show_top_languages'),),
        ),
        required=False,
    )

    mots_cles = SimpleArrayField(
        base_field=forms.CharField(max_length=50),
        label=_('Keywords'),
        required=False,
        widget=TagSelect2(
            attrs={
                'data-minimum-input-length': 1,
            },
        ),
    )

    type_modalites_diffusion = forms.ChoiceField(
        label=_('Distribution conditions'),
        required=False,
        choices=EMPTY_CHOICE + TypeModalitesDiffusionThese.choices(),
        help_text=_(
            'Access to the digital thesis may be open to the entire world, limited to the UCLouvain intranet or '
            'reserved solely for administrators. Access may also be blocked for a specific period of time, if the '
            'author prefers paper distribution for a certain period of time (e.g. two or three years).'
        ),
    )

    date_embargo = forms.DateField(
        label=_('End of the embargo period'),
        required=False,
        widget=CustomDateInput,
        help_text=_('At the end of the embargo period, the thesis becomes public.'),
    )

    limitations_additionnelles_chapitres = forms.CharField(
        label=_('Additional limitation for certain specific chapters'),
        required=False,
        widget=forms.Textarea,
        help_text=_(
            'Access may be restricted to certain parts of the thesis, for example to protect parts covered by '
            'confidentiality. Please specify this in this text area, mentioning the protected chapters and the '
            'type of access (restricted, forbidden, or embargo and date).'
        ),
    )

    accepter_conditions = forms.BooleanField(
        label=_('I accept'),
        required=False,
    )

    def __init__(self, person, *args, **kwargs):
        super().__init__(*args, **kwargs)

        # Initialize the fields with dynamic choices
        lang_code = self.data.get(self.add_prefix('langue_redaction_these'), self.initial.get('langue_redaction_these'))
        self.fields['langue_redaction_these'].choices = get_language_initial_choices(lang_code, person)

    def clean(self):
        cleaned_data = super().clean()

        if cleaned_data.get('langue_redaction_these') == LANGUAGE_UNDECIDED:
            self.add_error('langue_redaction_these', _('Please select a language.'))

        if cleaned_data.get('type_modalites_diffusion') != TypeModalitesDiffusionThese.ACCES_EMBARGO.name:
            cleaned_data['date_embargo'] = None

        return cleaned_data

contrib/forms/autocomplete.py
# ##############################################################################
#
#    OSIS stands for Open Student Information System. It's an application
#    designed to manage the core business of higher education institutions,
#    such as universities, faculties, institutes and professional schools.
#    The core business involves the administration of students, teachers,
#    courses, programs and so on.
#
#    Copyright (C) 2015-2025 Université catholique de Louvain (http://www.uclouvain.be)
#
#    This program is free software: you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation, either version 3 of the License, or
#    (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    A copy of this license - GNU General Public License - is available
#    at the root of the source code of this program.  If not,
#    see http://www.gnu.org/licenses/.
#
# ##############################################################################
from dal import autocomplete

__all__ = [
    'ListSelect2',
    'Select2',
    'TagSelect2',
]


# The media of the select2 widget are loaded in the base layout.html so we don't need to do it twice
class Select2WithoutMediaMixin:
    class Media:
        extend = False


class ListSelect2(Select2WithoutMediaMixin, autocomplete.ListSelect2):
    pass


class Select2(Select2WithoutMediaMixin, autocomplete.Select2):
    pass


class TagSelect2(Select2WithoutMediaMixin, autocomplete.TagSelect2):
    pass

contrib/forms/confirmation_paper.py
# ##############################################################################
#
#  OSIS stands for Open Student Information System. It's an application
#  designed to manage the core business of higher education institutions,
#  such as universities, faculties, institutes and professional schools.
#  The core business involves the administration of students, teachers,
#  courses, programs and so on.
#
#  Copyright (C) 2015-2022 Université catholique de Louvain (http://www.uclouvain.be)
#
#  This program is free software: you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation, either version 3 of the License, or
#  (at your option) any later version.
#
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.
#
#  A copy of this license - GNU General Public License - is available
#  at the root of the source code of this program.  If not,
#  see http://www.gnu.org/licenses/.
#
# ##############################################################################
from django import forms
from django.utils.translation import gettext_lazy as _

from parcours_doctoral.contrib.forms import CustomDateInput, DoctorateFileUploadField as FileUploadField


class PromoterConfirmationPaperForm(forms.Form):
    proces_verbal_ca = FileUploadField(
        label=_('Support Committee minutes'),
        required=False,
        max_files=1,
    )
    avis_renouvellement_mandat_recherche = FileUploadField(
        label=_('Opinion on research mandate renewal'),
        required=False,
        max_files=1,
        help_text=_(
            "To be uploaded if you have a F.R.S.-FNRS (including Televie), FRIA or FRESH grant. "
            "The canvas for this opinion is provided by your research fund."
        ),
    )


class ConfirmationPaperForm(PromoterConfirmationPaperForm):
    date = forms.DateField(
        label=_('Confirmation exam date'),
        required=True,
        widget=CustomDateInput(),
    )
    rapport_recherche = FileUploadField(
        label=_('Research report'),
        required=False,
        max_files=1,
    )

    class Media:
        js = ('jquery.mask.min.js',)

contrib/forms/manuscript_validation.py
# ##############################################################################
#
#  OSIS stands for Open Student Information System. It's an application
#  designed to manage the core business of higher education institutions,
#  such as universities, faculties, institutes and professional schools.
#  The core business involves the administration of students, teachers,
#  courses, programs and so on.
#
#  Copyright (C) 2015-2025 Université catholique de Louvain (http://www.uclouvain.be)
#
#  This program is free software: you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation, either version 3 of the License, or
#  (at your option) any later version.
#
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.
#
#  A copy of this license - GNU General Public License - is available
#  at the root of the source code of this program.  If not,
#  see http://www.gnu.org/licenses/.
#
# ##############################################################################
from django import forms
from django.utils.translation import gettext_lazy as _

from parcours_doctoral.constants import FIELD_REQUIRED_MESSAGE
from parcours_doctoral.contrib.enums import DecisionApprovalEnum


class ManuscriptValidationApprovalForm(forms.Form):
    decision = forms.ChoiceField(
        label=_('Decision'),
        choices=DecisionApprovalEnum.choices(),
        widget=forms.RadioSelect,
        required=True,
    )

    motif_refus = forms.CharField(
        label=_('Grounds for denied'),
        required=False,
        max_length=50,
    )

    commentaire_interne = forms.CharField(
        label=_('Internal comment'),
        required=False,
        widget=forms.Textarea(
            attrs={
                'rows': 5,
            },
        ),
        help_text=_('This comment will be visible only to administrators.'),
    )

    commentaire_externe = forms.CharField(
        label=_('Comment for the candidate'),
        required=False,
        widget=forms.Textarea(
            attrs={
                'rows': 5,
            },
        ),
        help_text=_('This comment will be visible to all users with access to this page.'),
    )

    def clean(self):
        data = super().clean()

        if data.get('decision') == DecisionApprovalEnum.DECLINED.name:
            if not data.get('motif_refus'):
                self.add_error('motif_refus', FIELD_REQUIRED_MESSAGE)
        else:
            data['motif_refus'] = ''

        return data

    class Media:
        js = ('js/dependsOn.min.js',)

contrib/forms/private_public_defenses.py
# ##############################################################################
#
#  OSIS stands for Open Student Information System. It's an application
#  designed to manage the core business of higher education institutions,
#  such as universities, faculties, institutes and professional schools.
#  The core business involves the administration of students, teachers,
#  courses, programs and so on.
#
#  Copyright (C) 2015-2025 Université catholique de Louvain (http://www.uclouvain.be)
#
#  This program is free software: you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation, either version 3 of the License, or
#  (at your option) any later version.
#
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.
#
#  A copy of this license - GNU General Public License - is available
#  at the root of the source code of this program.  If not,
#  see http://www.gnu.org/licenses/.
#
# ##############################################################################

from parcours_doctoral.contrib.forms.private_defense import (
    PrivateDefenseForm,
    PromoterPrivateDefenseForm,
)
from parcours_doctoral.contrib.forms.public_defense import (
    PromoterPublicDefenseForm,
    PublicDefenseForm,
)


class PrivatePublicDefensesForm(PrivateDefenseForm, PublicDefenseForm):
    pass


class PromoterPrivatePublicDefensesForm(PromoterPrivateDefenseForm, PromoterPublicDefenseForm):
    pass

templates/parcours_doctoral/forms/jury/external_approval.html
{% extends "parcours_doctoral/tab_layout.html" %}

{% load django_bootstrap5 i18n static parcours_doctoral osis_document_components %}

{% comment "License" %}
  * OSIS stands for Open Student Information System. It's an application
  * designed to manage the core business of higher education institutions,
  * such as universities, faculties, institutes and professional schools.
  * The core business involves the administration of students, teachers,
  * courses, programs and so on.
  *
  * Copyright (C) 2015-2025 Université catholique de Louvain (http://www.uclouvain.be)
  *
  * This program is free software: you can redistribute it and/or modify
  * it under the terms of the GNU General Public License as published by
  * the Free Software Foundation, either version 3 of the License, or
  * (at your option) any later version.
  *
  * This program is distributed in the hope that it will be useful,
  * but WITHOUT ANY WARRANTY; without even the implied warranty of
  * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
  * GNU General Public License for more details.
  *
  * A copy of this license - GNU General Public License - is available
  * at the root of the source code of this program.  If not,
  * see http://www.gnu.org/licenses/.
{% endcomment %}

{% block submit_button_affix %}{% endblock %}

{% block tabs_content %}
  {% panel _("Doctorate summary") %}
    {% if doctorate.archive %}
      {% get_file_url doctorate.archive.0 as file_url %}
      <a href="{{ file_url }}" class="btn btn-default" target="_blank">
        <span class="fa fa-file-download"></span>
        {% trans "Download as PDF" %}
      </a>
    {% else %}
      <p>{% trans "The summary of the doctorate in PDF format is not available." %}</p>
    {% endif %}
  {% endpanel %}

  {% if approval_form and approval_form.decision %}
    <form class="osis-form" method="post" action="">
      {% csrf_token %}

      {% include "parcours_doctoral/modal/prevent_quitting_modal.html" %}

      {% panel _("Proposal approved") %}
        {% bootstrap_form_errors approval_form %}
        <form class="osis-form approval-form" method="post" action="">
          {% csrf_token %}
          {% bootstrap_field approval_form.decision %}
          {% bootstrap_field approval_form.motif_refus %}
          <div class="row">
            <div class="col-md-6">
              {% bootstrap_field approval_form.commentaire_interne %}
            </div>
            <div class="col-md-6">
              {% bootstrap_field approval_form.commentaire_externe %}
            </div>
          </div>
          {% bootstrap_button button_type="submit" content=_("Submit my decision") name="approval_submit" button_class="btn btn-primary" %}
        </form>
      {% endpanel %}
    </form>
  {% endif %}

  {% panel _("President") %}
    <div class="list-group">
    {% for membre in membre_president %}
      <div class="list-group-item membre-container">{% include "parcours_doctoral/forms/jury/includes/member.html" %}</div>
    {% empty %}
      <div class="list-group-item">{% trans "You need to set a member as president." %}</div>
    {% endfor %}
    </div>
  {% endpanel %}

  {% panel _("Secretary") %}
    <div class="list-group">
    {% for membre in membre_secretaire %}
      <div class="list-group-item membre-container">{% include "parcours_doctoral/forms/jury/includes/member.html" %}</div>
    {% empty %}
      <div class="list-group-item">{% trans "You need to set a member as secretary." %}</div>
    {% endfor %}
    </div>
  {% endpanel %}

  {% panel _("Members") %}
    <div class="list-group">
    {% for membre in membres %}
      <div class="list-group-item membre-container">{% include "parcours_doctoral/forms/jury/includes/member.html" %}</div>
    {% endfor %}
    </div>
  {% endpanel %}
{% endblock tabs_content %}

{% block script %}
  {{ block.super }}
  {{ approval_form.media.js }}
  <script type="application/javascript">
  $(function () {
    // Hide the reason input if the promoter approves the proposition
    $('#id_motif_refus').length && $('#id_motif_refus').dependsOn({
      'input[name="decision"]': {
        values: ['DECLINED'],
      },
    }, {
      duration: 0,
    });

    document.dispatchEvent(new Event('refreshFormInitial'));
  });
  </script>
{% endblock %}

{% block style %}
  {{ block.super }}
  {{ approval_form.media.css }}
  <style>
    .approval-form textarea {
      resize: vertical;
    }

    .signature-item blockquote {
      margin: 10px 0 0;
    }

    .signature-item + .well dl,
    .signature-item + .well .media-list,
    .signature-item + .well .media-heading {
      margin-bottom: 0;
    }
  </style>
{% endblock %}

templates/parcours_doctoral/forms/jury/external_confirm.html
{% extends "admission/admission_layout.html" %}
{% load bootstrap3 i18n static admission enums %}

{% comment "License" %}
  * OSIS stands for Open Student Information System. It's an application
  * designed to manage the core business of higher education institutions,
  * such as universities, faculties, institutes and professional schools.
  * The core business involves the administration of students, teachers,
  * courses, programs and so on.
  *
  * Copyright (C) 2015-2025 Université catholique de Louvain (http://www.uclouvain.be)
  *
  * This program is free software: you can redistribute it and/or modify
  * it under the terms of the GNU General Public License as published by
  * the Free Software Foundation, either version 3 of the License, or
  * (at your option) any later version.
  *
  * This program is distributed in the hope that it will be useful,
  * but WITHOUT ANY WARRANTY; without even the implied warranty of
  * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
  * GNU General Public License for more details.
  *
  * A copy of this license - GNU General Public License - is available
  * at the root of the source code of this program.  If not,
  * see http://www.gnu.org/licenses/.
{% endcomment %}

{% block content %}
  {% block template_messages %}
    <div id="template-messages-container">
      {% include "template_messages.html" %}
    </div>
  {% endblock %}
{% endblock %}

templates/parcours_doctoral/forms/jury/jury.html
{% extends "parcours_doctoral/tab_layout.html" %}
{% load i18n parcours_doctoral doctorate_enums django_bootstrap5 %}

{% comment "License" %}
* OSIS stands for Open Student Information System. It's an application
* designed to manage the core business of higher education institutions,
* such as universities, faculties, institutes and professional schools.
* The core business involves the administration of students, teachers,
* courses, programs and so on.
*
* Copyright (C) 2015-2025 Université catholique de Louvain (http://www.uclouvain.be)
*
* This program is free software: you can redistribute it and/or modify
* it under the terms of the GNU General Public License as published by
* the Free Software Foundation, either version 3 of the License, or
* (at your option) any later version.
*
* This program is distributed in the hope that it will be useful,
* but WITHOUT ANY WARRANTY; without even the implied warranty of
* MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
* GNU General Public License for more details.
*
* A copy of this license - GNU General Public License - is available
* at the root of the source code of this program.  If not,
* see http://www.gnu.org/licenses/.
{% endcomment %}

{% block tab_content %}
  <h3>{% trans "Jury composition" %}</h3>
  {% if doctorate|can_make_action:'jury_add_approval' and approval_form and approval_form.decision %}
    {% include "parcours_doctoral/modal/prevent_quitting_modal.html" %}
    {% panel _("Jury approval") %}
      {% bootstrap_form_errors approval_form type='non_fields' %}
      <form class="osis-form approval-form" method="post" action="">
        {% csrf_token %}
        {% bootstrap_field approval_form.decision %}
        {% bootstrap_field approval_form.motif_refus %}
        <div class="row">
          <div class="col-md-6">
            {% bootstrap_field approval_form.commentaire_interne %}
          </div>
          <div class="col-md-6">
            {% bootstrap_field approval_form.commentaire_externe %}
          </div>
        </div>
        {% bootstrap_button button_type="submit" content=_("Submit my decision") name="approval_submit" button_class="btn btn-primary" %}
      </form>
    {% endpanel %}
  {% endif %}

  {% panel _("President") %}
    <div class="list-group">
    {% for membre in membre_president %}
      <div class="list-group-item membre-container flex-wrap">{% include "parcours_doctoral/forms/jury/includes/member.html" %}</div>
    {% empty %}
      {% if can_set_roles %}
        <div class="list-group-item">{% trans "You need to set a member as president." %}</div>
      {% else %}
        <div class="list-group-item">{% trans "There is no president set yet." %}</div>
      {% endif %}
    {% endfor %}
    </div>
  {% endpanel %}

  {% panel _("Secretary") %}
    <div class="list-group">
    {% for membre in membre_secretaire %}
      <div class="list-group-item membre-container flex-wrap">{% include "parcours_doctoral/forms/jury/includes/member.html" %}</div>
    {% empty %}
      {% if can_set_roles %}
        <div class="list-group-item">{% trans "You need to set a member as secretary." %}</div>
      {% else %}
        <div class="list-group-item">{% trans "There is no secretary set yet." %}</div>
      {% endif %}
    {% endfor %}
    </div>
  {% endpanel %}

  {% panel _("Members") %}
    <div class="list-group">
    {% for membre in membres %}
      <div class="list-group-item membre-container flex-wrap">{% include "parcours_doctoral/forms/jury/includes/member.html" %}</div>
    {% endfor %}
    </div>
  {% endpanel %}

  {% if membre_verificateur %}
    {% panel _("Auditor") %}
      <div class="list-group">
      {% for membre in membre_verificateur %}
        <div class="list-group-item membre-container flex-wrap">{% include "parcours_doctoral/forms/jury/includes/member.html" %}</div>
      {% endfor %}
      </div>
    {% endpanel %}
  {% endif %}

  {% if membre_cdd %}
    <div class="card">
      <div class="card-body">
        <h4 class="card-title">{% translate 'CDD Manager' %}</h4>
        <div class="list-group">
        {% for membre in membre_cdd %}
          <div class="list-group-item membre-container flex-wrap">{% include "parcours_doctoral/forms/jury/includes/member.html" %}</div>
        {% endfor %}
        </div>
      </div>
    </div>
  {% endif %}

  {% if membre_adre %}
    <div class="card">
      <div class="card-body">
        <h4 class="card-title">{% translate 'ADRE Manager' %}</h4>
        <div class="list-group">
        {% for membre in membre_adre %}
          <div class="list-group-item membre-container flex-wrap">{% include "parcours_doctoral/forms/jury/includes/member.html" %}</div>
        {% endfor %}
        </div>
      </div>
    </div>
  {% endif %}

  {% if add_form %}
  {% panel _("Add a new member") %}
    {% include "parcours_doctoral/forms/jury/includes/member_form.html" with form=add_form %}
  {% endpanel %}
  {% endif %}

  {% if doctorate|can_make_action:'jury_request_signatures' %}
    <div class="text-center">
      <button
        type="button"
        class="btn btn-success btn-lg"
        data-bs-toggle="modal"
        data-bs-target="#request-signatures-modal"
      >
        {% trans "Request signatures" %}
      </button>
    </div>

    {% include "parcours_doctoral/forms/jury/includes/request_signature_modal.html" %}
  {% endif %}

{% endblock %}

{% block script %}
  {{ block.super }}

  {% if approve_by_pdf_form %}
    {{ approve_by_pdf_form.media.js }}
  {% endif %}

  {% if approval_form %}
    {{ approval_form.media.js }}
    <script>
      $('#id_motif_refus').dependsOn({
        'input[name=decision]': { values: ['DECLINED'] },
      }, { duration: 0, valueOnDisable: '', });
    </script>
  {% endif %}

  {% if add_form %}
  {{ add_form.media.js }}
  <script>
    $(function () {
      $('#id_justification_non_docteur').closest('.mb-3').dependsOn({
        '#id_titre': { values: ['NON_DOCTEUR'] },
      }, { duration: 0, valueOnDisable: '', });
      $('.ucl_show').dependsOn({
        'input[name=institution_principale]': { values: ['UCL'] },
      }, { duration: 0, valueOnDisable: '', });
      $('.ucl_hide').dependsOn({
        'input[name=institution_principale]': { values: ['OTHER'] },
      }, { duration: 0, valueOnDisable: '', });
    });
  </script>
  {% endif %}
  {% if can_set_roles %}
  <script>
    $('.membre-role-submit').click(function(event) {
      event.preventDefault();
      event.stopPropagation();
      window.preventQuitting = false;
      const $form = $(this).closest('.btn-group').find('.membre-role-form');
      $form.find('input[name=role]').val($(this).attr('data-role'));
      $form.submit();
    });
  </script>
  {% endif %}
{% endblock %}

{% block style %}
  {{ block.super }}

  {% if add_form %}
    {{ add_form.media.css }}
  {% endif %}

  {% if approve_by_pdf_form %}
    {{ approve_by_pdf_form.media.css }}
  {% endif %}

  {% if approval_form %}
    {{ approval_form.media.css }}
  {% endif %}

  <style>
    #id_institution_principale .form-check {
     display: inline-block;
     margin-right: 1rem;
   }
  .membre-container {
    display: flex;
    justify-content: space-between;
    align-items: center;
  }
  </style>
{% endblock %}